/** Uses local Supabase protocol and Resend doubles; no external email is sent. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {startFixture} from './mock-supabase.mjs';
import {deliverEmail} from '../lib/mail.mjs';
let fixture,calls=[],answer=200,nativeFetch;
function inquiry(extra={}){const row={id:randomUUID(),data:{name:'QA Client',email:'client@example.invalid',message:'Procuro uma pedra <especial> & única.',requestType:'sourcing',destination:'Brasil',company:'',phone:'',productName:'The Ruby Ring'},email_status:'queued',created_at:new Date().toISOString(),...extra};fixture.state.tables.inquiries.push(row);return row;}
test.before(async()=>{process.env.NODE_ENV='test';delete process.env.VERCEL;fixture=await startFixture();process.env.SUPABASE_URL=fixture.url;process.env.SUPABASE_SECRET_KEY='sb_secret_test_only_fixture';nativeFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{if(String(url)==='https://api.resend.com/emails'){calls.push(options);if(answer==='network')throw Error('simulated-network');return new Response(JSON.stringify(answer===200?{id:'mail-test-id'}:{message:'do-not-leak-provider-data'}),{status:answer,headers:{'Content-Type':'application/json'}});}return nativeFetch(url,options);};});
test.beforeEach(()=>{calls=[];answer=200;process.env.RESEND_API_KEY='re_fixture_not_a_real_key';process.env.EMAIL_FROM='Hillkings <concierge@example.invalid>';});
test.after(async()=>{globalThis.fetch=nativeFetch;await fixture.close();});
test('Missing provider credentials preserve enquiry and record precise setup requirement',async()=>{delete process.env.RESEND_API_KEY;delete process.env.EMAIL_FROM;const row=inquiry();const d=await deliverEmail(row.id,'https://hillkings.vercel.app');assert.equal(d.status,'queued');assert.equal(calls.length,0);assert.match(row.last_error,/RESEND_API_KEY e EMAIL_FROM/);assert.equal(row.email_status,'queued');});
test('Recipient is the editable setting; reply-to is the customer; HTML is escaped',async()=>{fixture.state.tables.settings[0].data.contactEmail='new-recipient@example.invalid';const row=inquiry();const d=await deliverEmail(row.id,'https://hillkings.vercel.app');assert.equal(d.status,'sent');assert.equal(calls.length,1);const payload=JSON.parse(calls[0].body);assert.deepEqual(payload.to,['new-recipient@example.invalid']);assert.equal(payload.reply_to,'client@example.invalid');assert.equal(payload.from,process.env.EMAIL_FROM);assert.match(payload.html,/&lt;especial&gt; &amp; única/);assert.match(payload.text,/<especial> & única/);assert.equal(row.email_id,'mail-test-id');assert.equal(row.last_error,null);});
test('Already accepted message does not resend; retries use stable idempotency key',async()=>{const row=inquiry();await deliverEmail(row.id,'https://hillkings.vercel.app');await deliverEmail(row.id,'https://hillkings.vercel.app');assert.equal(calls.length,1);assert.ok(calls[0].headers['Idempotency-Key'].startsWith('hk-'+row.id));});
test('Unverified sender rejection never produces false sent status or exposes response body',async()=>{answer=403;const row=inquiry();assert.equal((await deliverEmail(row.id,'https://hillkings.vercel.app')).status,'failed');assert.equal(row.email_status,'failed');assert.match(row.last_error,/domínio verificado/);assert.doesNotMatch(row.last_error,/do-not-leak|re_fixture/);});
test('Authorization failures and rate limits have actionable private diagnostics',async()=>{for(const status of [401,429]){answer=status;const row=inquiry();await deliverEmail(row.id,'https://hillkings.vercel.app');assert.equal(row.email_status,'failed');assert.match(row.last_error,status===401?/RESEND_API_KEY/:/limite de envio/);}});
test('Network failure keeps enquiry; subsequent retry succeeds',async()=>{answer='network';const row=inquiry();assert.equal((await deliverEmail(row.id,'https://hillkings.vercel.app')).status,'failed');answer=200;assert.equal((await deliverEmail(row.id,'https://hillkings.vercel.app')).status,'sent');assert.equal(calls[0].headers['Idempotency-Key'],calls[1].headers['Idempotency-Key']);});
test('Stale sending lock is recovered; active sending lock prevents parallel notification',async()=>{let row=inquiry({email_status:'sending',email_attempt_at:new Date(Date.now()-180000).toISOString()});assert.equal((await deliverEmail(row.id,'https://hillkings.vercel.app')).status,'sent');row=inquiry({email_status:'sending',email_attempt_at:new Date().toISOString()});assert.equal((await deliverEmail(row.id,'https://hillkings.vercel.app')).status,'sending');assert.equal(calls.length,1);});
