import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,access} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {handler} from '../lib/app.mjs';
import {startFixture} from './mock-supabase.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
let fixture,server,base,cookie='',csrf='';
async function request(route,{method='GET',body,headers={}}={}){
 const h={...headers};if(method!=='GET'&&method!=='HEAD'){h.Origin=base;h['Content-Type']='application/json';}if(cookie)h.Cookie=cookie;if(csrf)h['X-CSRF-Token']=csrf;
 const r=await fetch(base+route,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body),redirect:'manual'});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;
}
async function j(route,opts){const r=await request(route,opts);return {status:r.status,data:await r.json()};}
const password='FixtureOnly_NotForDeployment_73';
test.before(async()=>{process.env.NODE_ENV='test';delete process.env.VERCEL;delete process.env.APP_URL;delete process.env.RESEND_API_KEY;delete process.env.EMAIL_FROM;fixture=await startFixture();process.env.SUPABASE_URL=fixture.url;process.env.SUPABASE_SECRET_KEY='sb_secret_test_only_fixture';process.env.ADMIN_INITIAL_PASSWORD=password;server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
test.after(async()=>{await new Promise(r=>server.close(r));await fixture.close();});
test('Cold import succeeds when any attempt to create/write a local directory is forbidden',()=>{
 const script=`import fs from 'node:fs';import {syncBuiltinESMExports} from 'node:module';for(const n of ['mkdirSync','writeFileSync','appendFileSync'])fs[n]=()=>{throw Error('Forbidden disk write')};syncBuiltinESMExports();await import('./api/index.mjs');console.log('import-ok');`;
 const r=spawnSync(process.execPath,['--input-type=module','-e',script],{cwd:process.cwd(),encoding:'utf8',env:{...process.env,SUPABASE_URL:'',SUPABASE_SECRET_KEY:'',VERCEL:'1',NODE_ENV:'production'}});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/import-ok/);
});
test('Without cloud config, public catalogue opens; backend refuses writes without claiming receipt',async()=>{
 delete process.env.SUPABASE_SECRET_KEY;try{const r=await request('/');assert.equal(r.status,200);assert.match(await r.text(),/catalog-only/);let d=await j('/api/health');assert.equal(d.data.databaseReady,false);d=await j('/api/inquiries',{method:'POST',body:{name:'Nobody'}});assert.equal(d.status,503);assert.match(d.data.error,/não foi enviada nem armazenada/);}finally{process.env.SUPABASE_SECRET_KEY='sb_secret_test_only_fixture';}
});
test('Native handler supports explicit Vercel catch-all rewrite',async()=>{const r=await request('/api/index?__hk_path=collection&lang=en');assert.equal(r.status,200);assert.match(await r.text(),/Hillkings/);});
test('Public pages and favicon routes render',async()=>{for(const route of ['/','/collection','/private','/contact','/admin','/piece/paraiba-2-09','/piece/colar-paraiba-2-61','/favicon.ico','/icons/favicon-32.png','/assets/admin.css'])assert.equal((await request(route)).status,200,route);});
test('Catalogue uses external store and preserves corrected prices, media labels, three models, private contact',async()=>{const d=await j('/api/catalog');assert.equal(d.status,200);assert.equal(d.data.mode,'live');assert.deepEqual(d.data.products.map(p=>p.priceCents),[50000000,20000000,21000000]);assert.ok(d.data.products.every(p=>p.modelUrl.endsWith('.glb')));const txt=JSON.stringify(d.data);assert.ok(!txt.includes('contactEmail'));assert.ok(!txt.includes('internalNotes'));assert.ok(!txt.includes('sb_secret'));});
test('All existing GLBs and byte ranges are unchanged and served',async()=>{for(const file of ['ruby-ring','paraiba-loose','paraiba-necklace']){const r=await request(`/models/${file}.glb`);assert.equal(r.status,200);const b=Buffer.from(await r.arrayBuffer());assert.equal(b.toString('ascii',0,4),'glTF');}const r=await request('/models/paraiba-loose.glb',{headers:{Range:'bytes=0-19'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,20);});
test('Known database outage does not silently serve seed prices',async()=>{fixture.state.failure=true;try{const d=await j('/api/catalog');assert.equal(d.status,503);assert.ok(!d.data.products);}finally{fixture.state.failure=false;}});
test('Untrusted Origin and anonymous administrative requests are rejected',async()=>{const r=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://attacker.invalid'},body:'{}'});assert.equal(r.status,403);assert.equal((await request('/api/admin/dashboard')).status,401);});
test('Initial administrator requires a safe environment password, not admin/admin',async()=>{process.env.ADMIN_INITIAL_PASSWORD='admin';try{assert.equal((await j('/api/admin/login',{method:'POST',body:{username:'admin',password:'admin'}})).status,503);assert.equal(fixture.state.tables.users.length,0);}finally{process.env.ADMIN_INITIAL_PASSWORD=password;}});
test('Initial login, compulsory change, CSRF protection, session invalidation',async()=>{
 let r=await j('/api/admin/login',{method:'POST',body:{username:'admin',password}});assert.equal(r.status,200);assert.equal(r.data.mustChange,true);csrf=r.data.csrf;const oldCookie=cookie;
 assert.equal((await request('/api/admin/dashboard')).status,428);
 const savedCsrf=csrf;csrf='wrong';r=await j('/api/admin/account',{method:'POST',body:{currentPassword:password,newPassword:'Another_Test_Only_Passphrase_32'}});assert.equal(r.status,403);csrf=savedCsrf;
 r=await j('/api/admin/account',{method:'POST',body:{username:'admin',currentPassword:password,newPassword:'Another_Test_Only_Passphrase_32'}});assert.equal(r.status,200);csrf=r.data.csrf;const newCookie=cookie;cookie=oldCookie;assert.equal((await request('/api/admin/dashboard')).status,401);cookie=newCookie;assert.equal((await request('/api/admin/dashboard')).status,200);
});
test('Product state writes use compare-and-set version checks',async()=>{let d=await j('/api/admin/dashboard');const p=d.data.products.find(p=>p.id==='HK-G001');let r=await j('/api/admin/products/'+p.id,{method:'PUT',body:{...p,status:'sold'}});assert.equal(r.status,200);assert.equal(r.data.product.status,'sold');r=await j('/api/admin/products/'+p.id,{method:'PUT',body:p});assert.equal(r.status,409);assert.equal(fixture.state.tables.products.find(p=>p.id==='HK-G001').data.status,'sold');});
test('A new handler server reads updates from external service rather than local files',async()=>{const second=http.createServer(handler);await new Promise(r=>second.listen(0,'127.0.0.1',r));try{const r=await fetch(`http://127.0.0.1:${second.address().port}/api/catalog`);const d=await r.json();assert.equal(d.products.find(x=>x.id==='HK-G001').status,'sold');}finally{await new Promise(r=>second.close(r));}});
test('Create, archive, and configurable email/WhatsApp work',async()=>{const d=(await j('/api/admin/dashboard')).data,p={...d.products[0],id:'HK-QA',slug:'qa-item',published:false};let r=await j('/api/admin/products',{method:'POST',body:p});assert.equal(r.status,201);r=await j('/api/admin/products/HK-QA',{method:'DELETE',body:{version:r.data.product.version}});assert.equal(r.data.product.status,'archived');r=await j('/api/admin/settings',{method:'PUT',body:{...d.settings,contactEmail:'qa@example.invalid',whatsapp:'5511999999999'}});assert.equal(r.status,200);assert.equal(r.data.settings.contactEmail,'qa@example.invalid');});
test('A signed direct GLB upload is validated before becoming an available asset',async()=>{
 const bytes=await readFile('public/models/paraiba-loose.glb');let r=await j('/api/admin/uploads/start',{method:'POST',body:{name:'model.glb',size:bytes.length}});assert.equal(r.status,201);const ticket=r.data;assert.ok(!JSON.stringify(ticket).includes('sb_secret'));
 assert.equal((await request('/uploads/'+ticket.name)).status,404);
 const put=await fetch(ticket.signedUrl,{method:'PUT',headers:{'Content-Type':ticket.contentType},body:bytes});assert.equal(put.status,200);
 r=await j('/api/admin/uploads/complete',{method:'POST',body:{name:ticket.name}});assert.equal(r.status,201);assert.equal(r.data.type,'model');const asset=await request(r.data.url);assert.equal(asset.status,302);assert.ok(asset.headers.get('location').startsWith(fixture.url));
});
test('Invalid upload type and mismatched content are rejected',async()=>{assert.equal((await j('/api/admin/uploads/start',{method:'POST',body:{name:'attack.html',size:100}})).status,400);const b=Buffer.from('NOT A JPEG');let r=await j('/api/admin/uploads/start',{method:'POST',body:{name:'fake.jpg',size:b.length}});const ticket=r.data;await fetch(ticket.signedUrl,{method:'PUT',headers:{'Content-Type':'image/jpeg'},body:b});r=await j('/api/admin/uploads/complete',{method:'POST',body:{name:ticket.name}});assert.ok([400,415].includes(r.status));assert.equal(fixture.state.tables.uploads.find(x=>x.name===ticket.name).status,'rejected');});
test('Concierge form persists externally before email configuration, with no false sent status',async()=>{const token=(await j('/api/contact-token')).data.token;await delay(1050);const r=await j('/api/inquiries',{method:'POST',body:{name:'QA Cliente',email:'qa@example.invalid',phone:'',requestType:'wholesale',destination:'Portugal',company:'QA Atelier',message:'Pedido de teste para compra no atacado.',productId:'HK-J002',consent:true,token}});assert.equal(r.status,201);assert.equal(r.data.emailStatus,'queued');const row=fixture.state.tables.inquiries.find(x=>x.id===r.data.id);assert.equal(row.data.requestType,'wholesale');const dash=(await j('/api/admin/dashboard')).data;assert.ok(dash.inquiries.find(x=>x.id===r.data.id));assert.equal(dash.emailConfigured,false);});
test('SQL limits access to server role, includes atomic account update and private storage',async()=>{const sql=await readFile('supabase/001_hillkings.sql','utf8');assert.match(sql,/revoke all.*from public,anon,authenticated/);assert.match(sql,/enable row level security/);assert.match(sql,/hk_change_account/);assert.match(sql,/'hillkings-media','hillkings-media',false/);assert.ok(!sql.includes('scrypt$'));});
test('No SQLite module or data folder is in deployment code; build contains release marker',async()=>{for(const p of ['api/index.mjs','lib/app.mjs','lib/cloud.mjs','lib/catalog.mjs'])assert.doesNotMatch(await readFile(p,'utf8'),/node:sqlite|mkdirSync\(|writeFileSync\(/);await assert.rejects(access('lib/database.mjs'));const r=JSON.parse(await readFile('dist/release.json','utf8'));assert.equal(r.localDatabase,false);assert.equal(r.release,'4.0.0-vercel-supabase');});
