/** Commercial figures supplied by the proprietor, not appraised here. Editorial media are explicitly labelled. */
export const initialSettings = {
  "brand": "Hillkings",
  "tagline": "Fine Gemstones",
  "whatsapp": "5511910815777",
  "contactEmail": "anderson@mediscope.com.br",
  "headline": "O extraordinário não se repete.",
  "headlineEn": "The extraordinary is never ordinary.",
  "intro": "Gemas singulares, joias para atravessar gerações. Uma curadoria pessoal — da coleção à busca sob encomenda, com atendimento para destinos em todo o mundo.",
  "introEn": "Singular gemstones, jewels for generations. Personal selection — from the collection to sourcing requests, with concierge service for destinations worldwide.",
  "conciergeText": "Concierge de joias e gemas sob encomenda. Atendimento individual, condições para atacado e entregas internacionais.",
  "legalName": "",
  "taxId": "",
  "address": "",
  "instagram": "",
  "showPrices": true,
  "showSold": true,
  "inquiryRetentionDays": 180,
  "featuredProductId": "HK-J001",
  "siteTitle": "Hillkings — Fine Gemstones",
  "description": "Hillkings Fine Gemstones: gemas e joias de luxo, concierge sob encomenda, condições para atacado e entregas internacionais. Conheça a coleção e fale com o concierge."
};
export const initialProducts = [
  {
    "id": "HK-J001",
    "slug": "anel-rubi-9-01",
    "name": "The Ruby Ring",
    "namePt": "Anel de rubi",
    "category": "jewellery",
    "status": "available",
    "published": true,
    "featured": true,
    "sortOrder": 1,
    "priceCents": 50000000,
    "currency": "USD",
    "priceOnRequest": false,
    "stone": "Rubi",
    "carats": "9,01",
    "secondary": "Diamantes · 1,40 ct · VVS",
    "metal": "Ouro branco",
    "cut": "Navete (marquise)",
    "origin": "Não informada",
    "dimensions": "Não informadas",
    "treatment": "A confirmar no relatório gemológico",
    "description": "Uma silhueta alongada, uma cor intensa e o encontro preciso entre o rubi central e os diamantes laterais. Uma peça para ser descoberta de perto.",
    "descriptionEn": "An elongated silhouette, a deep colour and the meeting of a central ruby with tapered side diamonds. A piece to discover up close.",
    "reportLab": "GIA",
    "reportNumber": "",
    "reportDate": "",
    "reportUrl": "",
    "reportState": "owner-reported",
    "reportNotes": "Existência de relatório GIA informada pelo proprietário. Cópia e escopo ainda não anexados; os 1,40 ct e a classificação VVS dos diamantes foram informados pelo proprietário.",
    "media": [
      {
        "url": "/media/ruby-detail.webp",
        "type": "image",
        "alt": "Fotografia real do anel de rubi com diamantes laterais",
        "kind": "original"
      },
      {
        "url": "/media/ruby-on-hand.webp",
        "type": "image",
        "alt": "Anel de rubi na mão, para referência de escala",
        "kind": "original"
      },
      {
        "url": "/media/ruby.mp4",
        "type": "video",
        "alt": "Vídeo real do anel de rubi",
        "poster": "/media/ruby-video-frame.webp",
        "kind": "original"
      }
    ],
    "heroImage": "/media/ruby-cutout.webp",
    "modelUrl": "/models/ruby-ring.glb",
    "modelKind": "approximation",
    "modelNotes": "Reconstrução visual aproximada do anel a partir das fotografias, com estudo óptico de refração e reflexos. Não é um CAD medido: lapidação, inclusões, proporções e resposta da cor não foram reproduzidas gemologicamente. Consulte as fotos, o vídeo e o relatório da peça real.",
    "internalNotes": "Quilatagem 9,01 ct; diamantes 1,40 ct VVS; preço informado pelo proprietário. Anexar laudo GIA do rubi, confirmar metal/teor, tratamentos, origem e classificação dos diamantes. Não associar o GIA 5141608096 a este anel."
  },
  {
    "id": "HK-G001",
    "slug": "paraiba-2-09",
    "name": "The Brazilian Paraíba",
    "namePt": "Turmalina Paraíba",
    "category": "gemstones",
    "status": "available",
    "published": true,
    "featured": true,
    "sortOrder": 2,
    "priceCents": 20000000,
    "currency": "USD",
    "priceOnRequest": false,
    "stone": "Turmalina Paraíba",
    "carats": "2,09",
    "secondary": "",
    "metal": "Gema solta",
    "cut": "Pera · coroa brilhante · pavilhão brilhante modificado",
    "origin": "Brasil — conforme relatório",
    "dimensions": "10,47 × 6,59 × 4,45 mm",
    "treatment": "Indícios de melhoria de pureza (clarity enhancement).",
    "description": "Uma turmalina verde-azulada de origem brasileira, apresentada em formato pera. A cor, o movimento e as particularidades da gema podem ser observados no vídeo original.",
    "descriptionEn": "A green-blue tourmaline of Brazilian origin, presented in a pear shape. Explore its colour, movement and individual characteristics in the original footage.",
    "reportLab": "GIA",
    "reportNumber": "5141608096",
    "reportDate": "2012-04-26",
    "reportUrl": "/media/gia-5141608096.jpg",
    "reportState": "document-provided",
    "reportNotes": "O relatório de 26/04/2012 identifica turmalina contendo cobre e manganês, que pode ser denominada “paraíba tourmaline” no comércio. Registra indícios de melhoria de pureza. O comentário informa que essa cor de turmalina é comumente aquecida e que a origem da cor desta pedra não pôde ser determinada. Cópia fornecida; confirmação online e correspondência com a gema física não verificadas aqui.",
    "media": [
      {
        "url": "/media/paraiba-editorial.webp",
        "type": "image",
        "kind": "editorial",
        "alt": "Apresentação editorial gerada por IA da Paraíba solta, isolada sobre fundo claro; consulte o vídeo da gema real."
      },
      {
        "url": "/media/paraiba-video-frame.webp",
        "type": "image",
        "alt": "Quadro extraído do vídeo real da turmalina Paraíba solta",
        "kind": "original"
      },
      {
        "url": "/media/paraiba.mp4",
        "type": "video",
        "alt": "Vídeo real da turmalina Paraíba solta",
        "poster": "/media/paraiba-video-frame.webp",
        "kind": "original"
      }
    ],
    "heroImage": "/media/paraiba-editorial.webp",
    "modelUrl": "/models/paraiba-loose.glb",
    "modelKind": "approximation",
    "modelNotes": "Reconstrução 3D ilustrativa. O envelope parte das medidas 10,47 × 6,59 × 4,45 mm informadas no relatório; lapidação, inclusões, cor e comportamento óptico não são medições desta gema. Consulte o vídeo real e o relatório.",
    "internalNotes": "Dados transcritos da imagem do relatório. Conferir no GIA Report Check e verificar se a pedra física corresponde ao relatório antes da venda. O relatório não é avaliação de preço. O tratamento foi lido diretamente na imagem, que diz INDICATIONS (não NO INDICATIONS)."
  },
  {
    "id": "HK-J002",
    "slug": "colar-paraiba-2-61",
    "name": "The Paraíba Necklace",
    "namePt": "Colar Paraíba",
    "category": "jewellery",
    "status": "available",
    "published": true,
    "featured": true,
    "sortOrder": 3,
    "priceCents": 21000000,
    "currency": "USD",
    "priceOnRequest": false,
    "stone": "Turmalina Paraíba",
    "carats": "2,61",
    "secondary": "Diamantes · peso a confirmar",
    "metal": "Ouro branco",
    "cut": "Pera",
    "origin": "Não informada",
    "dimensions": "Não informadas",
    "treatment": "A confirmar no relatório gemológico",
    "description": "A turmalina Paraíba ocupa o centro de uma composição delicada, contornada por diamantes. Uma joia de cor e presença, apresentada individualmente pelo atendimento Hillkings.",
    "descriptionEn": "A Paraíba tourmaline at the centre of a delicate composition, framed by diamonds. A jewel of colour and presence, presented individually by Hillkings.",
    "reportLab": "GIA",
    "reportNumber": "",
    "reportDate": "",
    "reportUrl": "",
    "reportState": "owner-reported",
    "reportNotes": "Existência de relatório GIA informada pelo proprietário. Cópia, número e escopo do relatório ainda não anexados. Origem, tratamentos e detalhes dos diamantes devem ser confirmados.",
    "media": [
      {
        "url": "/media/necklace-editorial.webp",
        "type": "image",
        "kind": "editorial",
        "alt": "Apresentação editorial gerada por IA do colar Paraíba isolado sobre fundo claro; montagem e detalhes não substituem o vídeo da joia real."
      },
      {
        "url": "/media/necklace-video-frame.webp",
        "type": "image",
        "alt": "Quadro extraído do vídeo real do colar Paraíba",
        "kind": "original"
      },
      {
        "url": "/media/necklace.mp4",
        "type": "video",
        "alt": "Vídeo real do colar Paraíba",
        "poster": "/media/necklace-video-frame.webp",
        "kind": "original"
      }
    ],
    "heroImage": "/media/necklace-editorial.webp",
    "modelUrl": "/models/paraiba-necklace.glb",
    "modelKind": "approximation",
    "modelNotes": "Reconstrução 3D ilustrativa do pingente com Paraíba e diamantes. Corrente, halo, garras, verso e proporções são aproximados, não CAD medido. Materiais e iluminação não reproduzem características gemológicas da peça real.",
    "internalNotes": "Preço corrigido pelo proprietário para US$ 210.000. Gema central 2,61 ct informada. Anexar GIA e completar diamantes, metal/teor, origem e tratamentos."
  }
];
